# - hosts: all
#   become: true
#   roles:
#     - basic

- hosts: webservers
  become: true
  roles:
    - webserver

- hosts: webservers
  become: true
  roles:
    - appserver

- hosts: webservers
  become: true
  roles:
    - dbserver
